---

- hosts: all
  become: true
  tasks:

  - name: install updates for CentOS
    yum:
      update_only: yes
      update_cache: yes
    when:
       - ansible_distribution == "CentOS"


  - name: install updates for Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when:
       - ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:


  - name: install http and php packages
    yum:
      name:
         - httpd
         - php
      state: latest
    when:
      - ansible_distribution == "CentOS"


  - name: instal apache2 and php
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
    when:
       - ansible_distribution == "Ubuntu"
