---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates for CentOS
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when:
       - ansible_distribution == "CentOS"


  - name: install updates for Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when:
       - ansible_distribution == "Ubuntu"


- hosts: workstations
  become: true
  tasks:


  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root




- hosts: web_servers
  become: true
  tasks:


  - name: install http and php packages
    tags: centos, apache, httpd
    yum:
      name:
         - httpd
         - php
      state: latest
    when:
      - ansible_distribution == "CentOS"


  - name: instal apache2 and php
    tags: ubuntu, apache, apache2
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
    when:
       - ansible_distribution == "Ubuntu"


  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:


  - name: install mariadb package for CentOS
    tags: db ,mariadb, centos
    yum:
      name: mariadb
      state: latest
    when:
      - ansible_distribution == "CentOS"


  - name: install mariadb package for Ubuntu
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when:
      - ansible_distribution == "Ubuntu"



- hosts: file_servers
  become: true
  tasks:


  - name: install samba package
    tags: samba
    package:
       name: samba
       state: latest 
